// scripts/build-sitemap.mjs
import fs from "node:fs/promises";

const BASE = (process.env.SITE_BASE_URL || "https://potus-countdown.vercel.app").replace(/\/+$/, "");
// Додай/зміни список сторінок за потреби:
const PAGES = [
  "/",               // index.html
  "/trump-today.html",
  "/digest.html",
  "/presidents.html",
  "/about.html",
  "/privacy.html",
  "/contact.html"
];

function isoDate(d = new Date()) {
  return d.toISOString();
}

async function main() {
  const lastmod = isoDate();
  const urls = PAGES.map((path) => {
    const loc = `${BASE}${path}`;
    return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>daily</changefreq>
    <priority>${path === "/" ? "1.0" : "0.7"}</priority>
  </url>`;
  }).join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build-sitemap.mjs -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  await fs.writeFile("sitemap.xml", xml, "utf8");
  console.log("sitemap.xml written for", BASE);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
