name: Generate digests

on:
  workflow_dispatch: {}   # спершу запускаємо вручну; розклад додамо потім

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIMEZONE: Europe/Kyiv
      LANGS: uk,de,fr,es
      DIGEST_MIN_ITEMS: '5'   # трохи нижче, щоб гарантовано згенерувалось
      OPENAI_MODEL: gpt-4o-mini
      SITE_ORIGIN: https://presidencyclock.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

            - name: Generate digests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FORCE: "true"          # можна прибрати пізніше
          DIGEST_MIN_ITEMS: "5"  # можна підняти пізніше
        run: |
          # Автовизначення, де лежить скрипт
          if [ -f potus-countdown/scripts/generate_digest.py ]; then
            python potus-countdown/scripts/generate_digest.py
          elif [ -f scripts/generate_digest.py ]; then
            python scripts/generate_digest.py
          else
            echo "Не знайшов generate_digest.py ні в potus-countdown/scripts/, ні в scripts/"
            ls -la
            exit 1
          fi

      - name: Commit & push
        run: |
          git config user.name "presidencyclock-bot"
          git config user.email "bot@presidencyclock.local"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "auto: digests $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
