name: Hotfix missing site files
on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Recreate folders and core files
        shell: bash
        run: |
          set -e

          # 0) технічні файли
          touch .nojekyll
          if ! grep -q '^presidencyclock\.com$' CNAME 2>/dev/null; then
            echo 'presidencyclock.com' > CNAME
          fi

          # 1) папки
          mkdir -p css js pages data

          # 2) CSS (мінімальний стиль, щоб усе гарно виглядало)
          cat > css/style.css <<'CSS'
          :root{--bg:#0b1020;--fg:#e8edf7;--muted:#9fb3c8;--accent:#3d6cff;--card:#121833;--card-border:#24305a}
          *{box-sizing:border-box}html,body{margin:0;padding:0;height:100%;font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,'Helvetica Neue',Arial;background:var(--bg);color:var(--fg)}
          a{color:var(--accent);text-decoration:none}
          header,footer{padding:14px 18px;border-bottom:1px solid var(--card-border)}
          header{display:flex;align-items:center;gap:14px}
          header img{height:32px}
          nav{margin-left:auto;display:flex;gap:12px;flex-wrap:wrap}
          nav a{padding:8px 10px;border:1px solid var(--card-border);border-radius:8px;background:rgba(255,255,255,.03)}
          nav a.active{border-color:var(--accent)}
          .container{max-width:1100px;margin:0 auto;padding:24px}
          .card{background:var(--card);border:1px solid var(--card-border);border-radius:14px;padding:16px}
          .hero{display:grid;grid-template-columns:1fr;gap:18px;margin-top:18px}
          .countdown{display:flex;gap:10px;flex-wrap:wrap}
          .tile{background:rgba(255,255,255,.03);border:1px solid var(--card-border);padding:16px 14px;border-radius:14px;min-width:110px;text-align:center}
          .num{font-size:32px;font-weight:800}
          .lbl{color:var(--muted);font-size:12px;letter-spacing:.05em;text-transform:uppercase}
          .controls{display:flex;gap:10px;flex-wrap:wrap;margin-top:6px}
          .btn{border:1px solid var(--card-border);background:rgba(255,255,255,.04);color:var(--fg);padding:10px 12px;border-radius:10px;cursor:pointer}
          .btn[aria-pressed="true"]{outline:2px solid var(--accent)}
          .lang-switch{display:flex;gap:8px}
          .ads{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin-top:14px}
          .ad-box{min-height:120px;background:rgba(255,255,255,.03);border:1px dashed var(--card-border);border-radius:10px;display:flex;align-items:center;justify-content:center;color:var(--muted)}
          footer{border-top:1px solid var(--card-border);border-bottom:none;color:var(--muted)}
          CSS

          # 3) JS: переклади
          cat > js/i18n.js <<'JS'
          window.I18N={
            en:{title:"Time left in Donald Trump’s presidency",sub:"U.S. presidential terms end at 12:00 noon ET on January 20 (Twentieth Amendment).",seconds:"Seconds",selectSound:"Sound",tickSound:"Ticking",beepSound:"Digital beep",unmute:"Unmute sound",mute:"Mute sound",shareX:"Share on X",shareFB:"Share on Facebook",copy:"Copy code",copied:"Copied!",evergreen:"Evergreen",digest:"AI Digest",about:"About",privacy:"Privacy",contact:"Contact",madeWith:"Made with",in:"in",kyiv:"Kyiv",termsNote:"Constitutional end of term: 12:00 ET, January 20, 2029."},
            uk:{title:"Скільки часу залишилося Дональду Трампу на посаді президента США",sub:"Президентський термін у США закінчується о 12:00 за Східним часом 20 січня (Двадцята поправка).",seconds:"Секунди",selectSound:"Звук",tickSound:"Тихий «тік-так»",beepSound:"Електронний біп",unmute:"Увімкнути звук",mute:"Вимкнути звук",shareX:"Поділитися в X",shareFB:"Поділитися у Facebook",copy:"Скопіювати код",copied:"Скопійовано!",evergreen:"Вічнозелений",digest:"AI-дайджест",about:"Про нас",privacy:"Політика конфіденційності",contact:"Зв'язок",madeWith:"Зроблено з",in:"у",kyiv:"Києві",termsNote:"Кінець терміну: 12:00 ET, 20 січня 2029."},
            es:{title:"Tiempo restante del mandato de Donald Trump",sub:"El mandato termina a las 12:00 ET el 20 de enero.",seconds:"Segundos",selectSound:"Sonido",tickSound:"Tictac",beepSound:"Pitido digital",unmute:"Activar sonido",mute:"Silenciar",shareX:"Compartir en X",shareFB:"Compartir en Facebook",copy:"Copiar código",copied:"¡Copiado!",evergreen:"Evergreen",digest:"AI Digest",about:"Acerca de",privacy:"Privacidad",contact:"Contacto",madeWith:"Hecho con",in:"en",kyiv:"Kyiv",termsNote:"Fin del mandato: 12:00 ET, 20 de enero de 2029."},
            fr:{title:"Temps restant du mandat de Donald Trump",sub:"Le mandat se termine à 12 h ET le 20 janvier.",seconds:"Secondes",selectSound:"Son",tickSound:"Tic-tac",beepSound:"Bip numérique",unmute:"Activer le son",mute:"Couper le son",shareX:"Partager sur X",shareFB:"Partager sur Facebook",copy:"Copier le code",copied:"Copié !",evergreen:"Evergreen",digest:"AI Digest",about:"À propos",privacy:"Confidentialité",contact:"Contact",madeWith:"Fait avec",in:"à",kyiv:"Kyiv",termsNote:"Fin du mandat : 12:00 ET, 20 janvier 2029."},
            de:{title:"Verbleibende Amtszeit von Donald Trump",sub:"Die Amtszeit endet um 12:00 ET am 20. Januar.",seconds:"Sekunden",selectSound:"Sound",tickSound:"Ticken",beepSound:"Digitaler Piepton",unmute:"Ton ein",mute:"Stumm",shareX:"Auf X teilen",shareFB:"Auf Facebook teilen",copy:"Code kopieren",copied:"Kopiert!",evergreen:"Evergreen",digest:"AI-Digest",about:"Über uns",privacy:"Datenschutz",contact:"Kontakt",madeWith:"Gemacht mit",in:"in",kyiv:"Kyiv",termsNote:"Amtsende: 12:00 ET, 20. Januar 2029."}
          };
          JS

          # 4) JS: звуки
          cat > js/audio.js <<'JS'
          class ClockAudio{
            constructor(){ this.ctx=null; this.enabled=false; this.mode='tick'; }
            ensure(){ if(!this.ctx) this.ctx=new (window.AudioContext||window.webkitAudioContext)(); }
            setMode(m){ this.mode=m; }
            toggle(on){ this.enabled=(on===undefined)?!this.enabled:on; if(this.enabled) this.ensure(); return this.enabled; }
            play(){ if(!this.enabled) return; this.ensure(); const o=this.ctx.createOscillator(), g=this.ctx.createGain();
              o.type='square'; o.frequency.value=(this.mode==='beep')?880:220;
              g.gain.value=0.001; g.gain.exponentialRampToValueAtTime(0.00001,this.ctx.currentTime+0.08);
              o.connect(g).connect(this.ctx.destination); o.start(); o.stop(this.ctx.currentTime+0.08);
            }
          }
          window.ClockAudio=ClockAudio;
          JS

          # 5) JS: логіка таймера (якщо твій app.js лежить у корені — скопіюємо; інакше створимо)
          if [ -f app.js ]; then
            cp -f app.js js/app.js
          else
            cat > js/app.js <<'JS'
            const TARGET_ISO_UTC='2029-01-20T17:00:00Z';
            const targetTs=Date.parse(TARGET_ISO_UTC);
            const qs=(s,el=document)=>el.querySelector(s);
            const qsa=(s,el=document)=>[...el.querySelectorAll(s)];
            const params=new URLSearchParams(location.search);
            let lang=(params.get('lang')||localStorage.getItem('lang')||(navigator.language||'en').split('-')[0]).toLowerCase();
            if(!window.I18N[lang]) lang='en';
            const t=k=>window.I18N[lang][k]||k;

            function applyI18n(){
              qsa('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
              const shareText=encodeURIComponent(t('title'));
              const url=encodeURIComponent(location.origin+location.pathname+'?lang='+lang);
              const x=qs('#share-x'), fb=qs('#share-fb');
              if(x) x.href=`https://twitter.com/intent/tweet?text=${shareText}&url=${url}`;
              if(fb) fb.href=`https://www.facebook.com/sharer/sharer.php?u=${url}`;
              document.title=t('title');
            }
            function switchLang(newLang){ lang=newLang; localStorage.setItem('lang',lang); applyI18n(); }

            const audio=new ClockAudio(); let muted=true; let mode='tick';
            function setSoundMode(m){ mode=m; audio.setMode(mode); qsa('.sound-option').forEach(b=>b.setAttribute('aria-pressed', b.dataset.mode===mode?'true':'false')); }
            function toggleMute(){ muted=!muted; audio.toggle(!muted); const btn=qs('#mute-btn'); if(btn) btn.textContent=muted?t('unmute'):t('mute'); }
            const pad=n=>String(n).padStart(2,'0');

            function renderCountdown(){
              const now=Date.now(); let diff=Math.max(0, targetTs-now);
              const sec=Math.floor(diff/1000)%60, min=Math.floor(diff/60000)%60, hr=Math.floor(diff/3600000)%24, day=Math.floor(diff/86400000);
              if(qs('#days .num')){ qs('#days .num').textContent=day; qs('#hours .num').textContent=pad(hr); qs('#minutes .num').textContent=pad(min); qs('#seconds .num').textContent=pad(sec); }
              if(!muted) audio.playTick?.() || audio.play?.();
              if(diff===0) clearInterval(timer);
            }
            let timer;
            function start(){
              applyI18n(); setSoundMode('tick'); renderCountdown(); timer=setInterval(renderCountdown,1000);
              qsa('[data-lang]').forEach(b=>b.addEventListener('click',()=>switchLang(b.dataset.lang)));
              qsa('.sound-option').forEach(b=>b.addEventListener('click',()=>setSoundMode(b.dataset.mode)));
              const mute=qs('#mute-btn'); if(mute) mute.addEventListener('click',toggleMute);
              const copy=qs('#copy-embed'); if(copy) copy.addEventListener('click',()=>navigator.clipboard.writeText(`<script src="${location.origin}/js/embed.js" data-lang="${lang}" data-theme="dark" async><\\/script>`).then(()=>{ copy.textContent=t('copied'); setTimeout(()=>copy.textContent=t('copy'),1200); }));
            }
            document.addEventListener('DOMContentLoaded',start);
            JS
          fi

          # 6) мінімальні сторінки, щоб не було 404
          cat > pages/about.html <<'HTML'
          <!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/css/style.css"><main class="container card"><h1>About</h1><p>Presidency Clock — мінімалістичний сайт зі зворотним відліком. Є віджет, 5 мов, evergreen та AI-дайджест.</p><p><a href="/">Home</a></p></main>
          HTML
          cat > pages/privacy.html <<'HTML'
          <!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/css/style.css"><main class="container card"><h1>Privacy</h1><p>No tracking by default. Ads via AdSense if увімкнені.</p><p><a href="/">Home</a></p></main>
          HTML
          cat > pages/contact.html <<'HTML'
          <!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/css/style.css"><main class="container card"><h1>Contact</h1><p><a href="mailto:presidencyclock@gmail.com">presidencyclock@gmail.com</a></p><p><a href="/">Home</a></p></main>
          HTML
          cat > pages/digest.html <<'HTML'
          <!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/css/style.css"><main class="container card"><h1>AI Digest</h1><p>Digest data will appear here (data/digest.json). </p><p><a href="/">Home</a></p></main>
          HTML
          cat > pages/evergreen.html <<'HTML'
          <!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/css/style.css"><main class="container card"><h1>Evergreen</h1><p>Tables will be rendered from /data/evergreen/*.json.</p><p><a href="/">Home</a></p></main>
          HTML

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "hotfix: recreate css/js/pages + nojekyll + CNAME"
            git push
          else
            echo "Nothing to commit."
          fi
