name: Update Trump Today

on:
  schedule:
    - cron: "30 20 * * *"   # 20:30 UTC щодня (зміниш за потреби)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run fetch script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_BASE: ${{ secrets.OPENAI_BASE }}
        run: node scripts/fetch-trump-today.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trump-today.json
          git commit -m "chore: update trump-today [skip ci]" || echo "No changes"
          git push
