name: Build Sitemap

on:
  schedule:
    - cron: "17 2 * * *"  # щодня о 02:17 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build sitemap
        env:
          SITE_BASE_URL: ${{ vars.SITE_BASE_URL }}
        run: node scripts/build-sitemap.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "chore: update sitemap [skip ci]" || echo "No changes"
          git push
